const state={machines:[],processes:[]};
const $=id=>document.getElementById(id); const esc=value=>String(value).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
async function api(path, body){const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error);return data}
function render(){
 $('machines').innerHTML=state.machines.length?state.machines.map(m=>`<article class="machine"><strong>${esc(m.name)}</strong><span>${m.capacity} units/s</span><small>Ready queue: ${m.queue?.length||0}</small></article>`).join(''):'<p class="muted">No virtual machines added.</p>';
 $('processes').innerHTML=state.processes.length?state.processes.map(p=>`<tr><td>${p.id}</td><td>${esc(p.name)}</td><td>${p.matches??'—'}</td><td>${p.priority}</td><td>${p.estimated_time??'—'}</td><td>${p.status||'Queued'}</td></tr>`).join(''):'<tr><td colspan="6" class="muted">No submitted processes.</td></tr>';
}
async function refresh(){let d=await fetch('/api/state').then(r=>r.json());state.machines=d.machines;state.processes=d.processes;render()}
$('machine-form').onsubmit=async e=>{e.preventDefault();try{let f=new FormData(e.target);await api('machines',Object.fromEntries(f));e.target.reset();$('message').textContent='Virtual machine added.';refresh()}catch(x){$('message').textContent=x.message}};
$('process-form').onsubmit=async e=>{e.preventDefault();try{let f=new FormData(e.target);await api('processes',Object.fromEntries(f));e.target.reset();$('message').textContent='Process submitted; KMP match positions calculated.';refresh()}catch(x){$('message').textContent=x.message}};
function showMetrics(metrics){$('metrics').innerHTML=Object.entries(metrics).filter(([k])=>k!=='machine_utilization').map(([k,v])=>`<article class="metric"><small>${k.replaceAll('_',' ')}</small><strong>${v}</strong></article>`).join('')+Object.entries(metrics.machine_utilization||{}).map(([n,v])=>`<article class="metric"><small>${n} utilization</small><strong>${v}%</strong></article>`).join('')}
$('run').onclick=async()=>{try{let d=await api('simulate',{algorithm:$('algorithm').value});state.machines=d.machines;state.processes=d.processes;render();showMetrics(d.metrics);$('message').textContent=`${d.algorithm} simulation complete.`}catch(x){$('message').textContent=x.message}};
$('compare').onclick=async()=>{try{let d=await api('compare',{});$('metrics').innerHTML=Object.entries(d).map(([a,m])=>`<article class="metric"><strong>${a}</strong><small>Wait: ${m.average_waiting_time}s</small><small>Turnaround: ${m.average_turnaround_time}s</small><small>Makespan: ${m.makespan}s</small></article>`).join('');$('message').textContent='Comparison complete.'}catch(x){$('message').textContent=x.message}};
refresh().catch(()=>{$('message').textContent='Start Python backend: python backend/app.py';render()});
