const state={machines:[],processes:[]};
const $=id=>document.getElementById(id); const esc=value=>String(value).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
async function api(path,body={},method='POST'){const r=await fetch('/api/'+path,{method,headers:{'Content-Type':'application/json'},body:method==='DELETE'?undefined:JSON.stringify(body)});const data=await r.json();if(!r.ok)throw Error(data.error);return data}
function render(){
 $('machines').innerHTML=state.machines.length?state.machines.map(m=>`<article class="machine"><strong>${esc(m.name)}</strong><span>${m.capacity} chars/s</span><small>Ready queue: ${m.queue?.length||0}</small><button class="delete-vm" data-id="${m.id}">Delete VM</button></article>`).join(''):'<p class="muted">No virtual machines added.</p>';
 $('processes').innerHTML=state.processes.length?state.processes.map(p=>`<tr><td>${p.id}</td><td>${esc(p.name)}</td><td>${p.matches??'-'}</td><td>${p.priority}</td><td>${p.processing_time||'-'}</td><td>${p.status||'Queued'}</td></tr>`).join(''):'<tr><td colspan="6" class="muted">No submitted processes.</td></tr>';
 document.querySelectorAll('.delete-vm').forEach(button=>button.onclick=async()=>{try{await api(`machines/${button.dataset.id}`,{},'DELETE');$('message').textContent='Virtual machine deleted.';refresh()}catch(x){$('message').textContent=x.message}});
}
async function refresh(){let d=await fetch('/api/state').then(r=>r.json());state.machines=d.machines;state.processes=d.processes;render()}
$('machine-form').onsubmit=async e=>{e.preventDefault();try{let f=new FormData(e.target);await api('machines',Object.fromEntries(f));e.target.reset();$('message').textContent='Virtual machine added.';refresh()}catch(x){$('message').textContent=x.message}};
$('process-form').onsubmit=async e=>{e.preventDefault();try{let f=new FormData(e.target);await api('processes',Object.fromEntries(f));e.target.reset();$('message').textContent='Process submitted. Positions will be calculated during simulation.';refresh()}catch(x){$('message').textContent=x.message}};
function showMetrics(metrics){$('metrics').innerHTML=Object.entries(metrics).filter(([k])=>k!=='machine_utilization').map(([k,v])=>`<article class="metric"><small>${k.replaceAll('_',' ')}</small><strong>${v}</strong></article>`).join('')+Object.entries(metrics.machine_utilization||{}).map(([n,v])=>`<article class="metric"><small>${n} utilization</small><strong>${v}%</strong></article>`).join('')}
async function watchSimulation(){const stateResponse=await fetch('/api/simulation').then(r=>r.json());await refresh();if(stateResponse.running){setTimeout(watchSimulation,350);return}if(stateResponse.result?.status===200){showMetrics(stateResponse.result.result.metrics);$('message').textContent=`${stateResponse.result.result.algorithm} simulation complete.`}else $('message').textContent='Simulation could not complete.'}
$('run').onclick=async()=>{try{await api('simulate',{algorithm:$('algorithm').value});$('message').textContent='Simulation running...';watchSimulation()}catch(x){$('message').textContent=x.message}};
$('compare').onclick=async()=>{try{let d=await api('compare',{});$('metrics').innerHTML=Object.entries(d).map(([a,m])=>`<article class="metric comparison"><strong>${a}</strong><small>Wait: ${m.average_waiting_time}s</small><small>Turnaround: ${m.average_turnaround_time}s</small><small>Makespan: ${m.makespan}s</small></article>`).join('');$('message').textContent='Comparison complete.'}catch(x){$('message').textContent=x.message}};
refresh().catch(()=>{$('message').textContent='Start Python backend: python backend/app.py';render()});
